// This file is auto-generated by @hey-api/openapi-ts

export const $PersonModel = {
    title: 'PersonModel',
    description: 'PersonModel',
    required: ['id', 'name', 'organization_id', 'assessment_period_id', 'completed', 'created_by', 'updated_by'],
    properties: {
        id: {
            description: 'Action Plan ID',
            type: 'integer',
            format: 'int32'
        },
        name: {
            description: 'Action Plan ID',
            type: 'integer',
            format: 'int32'
        }
    },
    type: 'object'
} as const;

export const $SupplierModel = {
    title: 'SupplierModel',
    description: 'SupplierModel',
    required: ['id', 'name', 'organization_id', 'assessment_period_id', 'completed', 'created_by', 'updated_by'],
    properties: {
        id: {
            description: 'Action Plan ID',
            type: 'integer',
            format: 'int32'
        },
        name: {
            description: 'Action Plan ID',
            type: 'integer',
            format: 'int32'
        },
        days_of_invoices: {
            description: 'Days of Invoices',
            type: 'integer',
            format: 'int32'
        }
    },
    type: 'object'
} as const;

export const $Suppliers = {
    type: 'array',
    items: {
        '$ref': '#/components/schemas/SupplierModel'
    }
} as const;