// This file is auto-generated by @hey-api/openapi-ts

/**
 * PersonModel
 */
export type PersonModel = {
    /**
     * Action Plan ID
     */
    id: number;
    /**
     * Action Plan ID
     */
    name: number;
};

/**
 * SupplierModel
 */
export type SupplierModel = {
    /**
     * Action Plan ID
     */
    id: number;
    /**
     * Action Plan ID
     */
    name: number;
    /**
     * Days of Invoices
     */
    days_of_invoices?: number;
};

export type Suppliers = Array<SupplierModel>;

export type PostAuthLoginResponse = unknown;

export type PostAuthMeResponse = unknown;

export type PostAuthLogoutResponse = unknown;

export type GetClientsData = {
    /**
     * Pocet zaznamov na jednu stranku
     */
    count?: string;
};

export type GetClientsResponse = unknown;

export type GetClientsByIdData = {
    /**
     * ID klienta ktoreho data chceme ziskat
     */
    id: string;
};

export type GetClientsByIdResponse = unknown;

export type GetSuppliersBySuppidContactPersonsData = {
    /**
     * ID dodavatela
     */
    suppid: number;
};

export type GetSuppliersBySuppidContactPersonsResponse = unknown;

export type PostSuppliersBySuppidContactPersonsData = {
    /**
     * ID dodavatela
     */
    suppid: number;
};

export type PostSuppliersBySuppidContactPersonsResponse = unknown;

export type GetSuppliersBySuppidContactPersonsByIdData = {
    /**
     * ID kontaktnej osoby
     */
    id: number;
    /**
     * ID dodavatela
     */
    suppid: number;
};

export type GetSuppliersBySuppidContactPersonsByIdResponse = unknown;

export type DeleteSuppliersBySuppidContactPersonsByIdData = {
    /**
     * ID kontaktnej osoby
     */
    id: number;
    /**
     * ID dodavatela
     */
    suppid: number;
};

export type DeleteSuppliersBySuppidContactPersonsByIdResponse = unknown;

export type PatchSuppliersBySuppidContactPersonsByIdData = {
    /**
     * ID kontaktnej osoby
     */
    id: number;
    /**
     * ID dodavatela
     */
    suppid: number;
};

export type PatchSuppliersBySuppidContactPersonsByIdResponse = unknown;

export type GetSuppliersResponse = Suppliers;

export type PostSuppliersResponse = unknown;

export type GetSuppliersByIdData = {
    /**
     * ID dodavatela
     */
    id: number;
};

export type GetSuppliersByIdResponse = SupplierModel;

export type DeleteSuppliersByIdData = {
    /**
     * ID dodavatela
     */
    id: number;
};

export type DeleteSuppliersByIdResponse = unknown;

export type PatchSuppliersByIdData = {
    /**
     * ID dodavatela
     */
    id: number;
};

export type PatchSuppliersByIdResponse = unknown;

export type GetApiUsersResponse = unknown;

export type $OpenApiTs = {
    '/auth/login': {
        post: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/auth/me': {
        post: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/auth/logout': {
        post: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/clients': {
        get: {
            req: GetClientsData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/clients/{id}': {
        get: {
            req: GetClientsByIdData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/suppliers/{suppid}/contact-persons': {
        get: {
            req: GetSuppliersBySuppidContactPersonsData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
        post: {
            req: PostSuppliersBySuppidContactPersonsData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/suppliers/{suppid}/contact-persons/{id}': {
        get: {
            req: GetSuppliersBySuppidContactPersonsByIdData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
        delete: {
            req: DeleteSuppliersBySuppidContactPersonsByIdData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
        patch: {
            req: PatchSuppliersBySuppidContactPersonsByIdData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/suppliers': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Suppliers;
            };
        };
        post: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/suppliers/{id}': {
        get: {
            req: GetSuppliersByIdData;
            res: {
                /**
                 * OK
                 */
                200: SupplierModel;
            };
        };
        delete: {
            req: DeleteSuppliersByIdData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
        patch: {
            req: PatchSuppliersByIdData;
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/api/users': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
};