#!/bin/sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if [ -f .nvmrc ] && [ -s "$NVM_DIR/nvm.sh" ]; # $NVM_DIR/nvm.sh
then
  . "$NVM_DIR/nvm.sh"
  nvm use
fi;

. "$(dirname "$0")/_/husky.sh"

yarn lint-staged
